CREATE TABLE user_roles (
  user_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  role         VARCHAR(45) NOT NULL,
  username     INTEGER     NOT NULL,
  PRIMARY KEY (user_role_id)
);
CREATE TABLE users (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  enabled  BOOLEAN     NOT NULL,
  password VARCHAR(60) NOT NULL,
  username VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);